name: ci-release
description: custom ci release action

inputs:
  github_token:
     description: "github secret"
     required: true

  access_token:
    description: "full accesss auth token"
    required: false

  as:
    description: 'bump version kind'
    required: true
    default: 'patch'

  registry:
    description: 'should publish to npm package'
    required: false
    default: 'false'

  build:
    description: "run yarn build automatically to generate dist"
    default: 'false'

  node:
    description: "node version to use"
    default: '20'

runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        registry-url: 'https://npm.pkg.github.com'
        node-version: ${{ inputs.node }}

    - name: Git authentication
      shell: bash
      run: |
          git config --global user.email "user@release.com"
          git config --global user.name "user CI"

    - name: Install dependencies
      run: corepack enable && yarn set version stable && YARN_ENABLE_IMMUTABLE_INSTALLS=false ACCESS_TOKEN=${{ inputs.access_token }} yarn install
      shell: bash

    - name: Bump version, tag and create changelog
      shell: bash
      run: npx standard-version --release-as ${{ inputs.as }}

    - name: Push changes
      shell: bash
      run: git push --follow-tags

    - name: Build dependencies
      if: ${{ inputs.build == 'true' }}
      shell: bash
      run: yarn build

    - name: Publish version
      if: ${{ inputs.registry == 'true'}}
      shell: bash
      run: yarn npm publish
      env:
        ACCESS_TOKEN: ${{ inputs.github_token }}
